### PR TITLE
Bug fixes for Menu update and Migration

### PR DESCRIPTION
**Pull request by rubensrocha**

### CODE REVIEW

**Comment by agungsugiarto** [comment]
Hallo @rubensrocha, can you only pr for fix migration? i will fix for to handle delete cache because will be better to trigger with model. Thanks.

**Comment by agungsugiarto** [comment]
Hmm can you explain why to delete migrate -all? i think migrate -all is to call migration for all namespace. If you need some update migration you can add with paramater command php spark migrate:refresh -all .

**Comment by rubensrocha** [comment]
> Hmm can you explain why to delete migrate -all? i think migrate -all is to call migration for all namespace. If you need some update migration you can add with paramater command php spark migrate:refresh -all .

When I deleted the database and ran `php spark boilerplate: install` two error messages always appear.

```Table 'auth_reset_attempts' already exists
Table '{database_name_here}.menu' doesn't exist```

Moving the menu migration to the project and removing the `-all` parameter works perfectly.

**Comment by rubensrocha** [comment]
I imagine it is a conflict because of Myth, his "publish" command moves the migration to the project, "boilerplate:install" command does not move the menu migration. So, using the "-all" parameter, CI certainly tries to migrate Myth migration twice, the one he moved to the project and the original contained in the vendor package.

**Comment by agungsugiarto** [comment]
> 
> 
> I imagine it is a conflict because of Myth, his "publish" command moves the migration to the project, "boilerplate:install" command does not move the menu migration. So, using the "-all" parameter, CI certainly tries to migrate Myth migration twice, the one he moved to the project and the original contained in the vendor package.

Oke thanks, i will be edit guide for publish first migration myth.

**Comment by rubensrocha** [comment]
> > I imagine it is a conflict because of Myth, his "publish" command moves the migration to the project, "boilerplate:install" command does not move the menu migration. So, using the "-all" parameter, CI certainly tries to migrate Myth migration twice, the one he moved to the project and the original contained in the vendor package.
> 
> Oke thanks, i will be edit guide for publish first migration myth.

Now that I have created the command to publish your package migrations, you can keep it as it was before. Removing the "-all" parameter already resolves the conflict with MythAuth, and that way it is better because if the person installs another package that also has migrations, it will prevent the same problem from happening.

**Pull request merged**
