### PR TITLE
added some badges on readme.md

### PR DESCRIPTION
**Pull request by truelineinfotech**
added some badges like fork, downloads, starts, issues and licence

### CODE REVIEW

**Comment by agungsugiarto** [comment]
Hy dude this project is early on development, but thanks. I will setup if already.

**Comment by truelineinfotech** [comment]
okay. btw thanks for sharing nice code. its amazing.

**Comment by agungsugiarto** [comment]
Hello wanna try ? This demo on
[heroku](https://boilerplate-codeigniter4.herokuapp.com/admin)

`username: admin
password: super-admin`

**Comment by truelineinfotech** [comment]
thanks for the info. i really appreciate your work. i would like to depth study of boilerplate code.

**Comment by truelineinfotech** [comment]
finally you added badges... haha.

**Comment by agungsugiarto** [comment]
hehe yes finnally, but with lot of bug lmao

**Pull request closed without merging**
